#!/bin/bash
# Quick viewer for all comparison grids

echo "======================================================================"
echo "🎨 ALL CATEGORIES COMPARISON GRIDS VIEWER"
echo "======================================================================"
echo ""
echo "📊 Total Grids: 16 (covering all 125 Sketchy categories)"
echo "📁 Location: /workspace/comparison_grid_XX.png"
echo ""
echo "======================================================================"

# List all grids with sizes
echo ""
echo "📋 Available Grids:"
echo ""
ls -lh /workspace/comparison_grid_*.png | awk '{print "   " $9 " (" $5 ")"}'

echo ""
echo "======================================================================"
echo "🖼️  To View:"
echo "======================================================================"
echo ""
echo "Method 1: Download all grids from /workspace/"
echo "   - comparison_grid_01.png through comparison_grid_16.png"
echo ""
echo "Method 2: View in VS Code"
echo "   - Open workspace folder"
echo "   - Click on any comparison_grid_XX.png file"
echo ""
echo "Method 3: Use image viewer (if available)"
echo "   feh /workspace/comparison_grid_*.png"
echo ""
echo "======================================================================"
echo "📊 Grid Layout:"
echo "======================================================================"
echo ""
echo "Each grid shows 8 categories in format:"
echo ""
echo "  ┌──────────┬──────────┬──────────┬──────────┐"
echo "  │ Sketch 1 │ Sketch 2 │ Sketch 3 │ ... (8) │"
echo "  ├──────────┼──────────┼──────────┼─────────┤"
echo "  │  Gen 1   │  Gen 2   │  Gen 3   │ ... (8) │"
echo "  └──────────┴──────────┴──────────┴─────────┘"
echo ""
echo "  Top Row: Original sketches from dataset"
echo "  Bottom Row: Generated photorealistic images"
echo ""
echo "======================================================================"
echo "✅ All 125 categories tested successfully!"
echo "======================================================================"
